#!/usr/bin/env node
/* eslint-disable no-console */
'use strict';
const fs=require('fs'); const path=require('path');
const { classifyAudience, audienceFrame, AUTHORITY_DOMAIN, CTA_TARGET } = require('../lib/audience_frame');
const ROOT=process.cwd();
const INPUTS=['data/community/scored_signals.json','data/social/routed_candidates.json','data/social/runs'];
const OUT='data/community/content_routing_log.json';
const MEMORY='data/content_clusters/cluster_memory.json';
function readJson(p,f){try{return JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'))}catch{return f}}
function writeJson(p,o){const f=path.join(ROOT,p); fs.mkdirSync(path.dirname(f),{recursive:true}); fs.writeFileSync(f,JSON.stringify(o,null,2)+'\n')}
function slug(s){return String(s||'general').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,72)||'general'}
function textOf(s){return `${s.normalized_query||''} ${s.query||''} ${s.title||''} ${s.raw_title||''} ${s.short_excerpt||''} ${s.excerpt||''}`.trim()}
function intentType(text){const v=String(text||'').toLowerCase(); if(/betterup|hone|culture amp|alternative|vs|compare|comparison/.test(v)) return 'comparison'; if(/download|cost|price|buy|gumroad|worth it/.test(v)) return 'conversion'; if(/burnout|overwhelmed|reset|motivation low|stuck/.test(v)) return 'recovery'; if(/discipline|habit|consistent|accountability|daily routine/.test(v)) return 'discipline'; if(/ai coach|ai executive coach|chatgpt|automation/.test(v)) return 'ai_coaching'; return 'execution';}
function destinationFor(signal,intent,cluster){const rec=signal.publish_recommendation||signal.scoring?.publish_recommendation||signal.status||''; const score=Number(signal.total_score||signal.scoring?.total_score||signal.score||0); if(rec==='discard') return 'memory'; if(intent==='comparison') return 'comparison'; if(score>=40 || /state-of|landscape|research|report/.test(cluster)) return 'authority'; if(rec==='publish' || score>=12) return 'insight'; return 'synthesis';}
function canonicalTarget(dest,cluster){ if(dest==='comparison') return `${AUTHORITY_DOMAIN}/compare/${cluster}.html`; if(dest==='authority') return `${AUTHORITY_DOMAIN}/whitepapers/${cluster}.html`; if(dest==='synthesis') return `${AUTHORITY_DOMAIN}/synthesis-${cluster}.html`; if(dest==='insight') return `${AUTHORITY_DOMAIN}/insights/${cluster}.html`; return AUTHORITY_DOMAIN;}
function loadSignals(){let rows=[]; const scored=readJson('data/community/scored_signals.json',[]); if(Array.isArray(scored)) rows=rows.concat(scored); const socialDir=path.join(ROOT,'data/social/runs'); if(fs.existsSync(socialDir)){for(const f of fs.readdirSync(socialDir).filter(x=>x.endsWith('.json')).sort().slice(-14)){const run=JSON.parse(fs.readFileSync(path.join(socialDir,f),'utf8')); rows=rows.concat((run.records||[]).map(x=>({...x,source_run:f})));}} const reddit=readJson('data/reddit/queries.json',{queries:[]}); rows=rows.concat((reddit.queries||[]).map((q,i)=>({signal_id:`reddit_query_${i}`,source:'reddit',platform:'reddit',query:q.query||q.title||'',cluster:q.cluster_hint||q.cluster||'',intent:q.intent||''}))); return rows;}
function main(){const rows=loadSignals(); const routed=[]; const clusters=new Map(); for(const s of rows){const text=textOf(s); if(!text) continue; const audience=classifyAudience(text); const frame=audienceFrame(audience,text); const intent=intentType(text); const cluster=slug(s.cluster||s.scoring?.cluster||intent+'-'+audience); const destination_type=destinationFor(s,intent,cluster); const route={signal_id:s.signal_id||s.normalized_id||slug(text).slice(0,32),source:s.source||s.platform||s.source_key||'unknown',query:text.slice(0,240),audience,intent,destination_type,cluster_id:cluster,canonical_target:canonicalTarget(destination_type,cluster),cta_target:CTA_TARGET,audience_frame:frame,created_at:new Date().toISOString()}; routed.push(route); const c=clusters.get(cluster)||{cluster_id:cluster,signal_count:0,audiences:{},intents:{},routes:{},canonical_target:route.canonical_target,cta_target:CTA_TARGET,status:'emerging'}; c.signal_count++; c.audiences[audience]=(c.audiences[audience]||0)+1; c.intents[intent]=(c.intents[intent]||0)+1; c.routes[destination_type]=(c.routes[destination_type]||0)+1; c.last_updated=new Date().toISOString(); c.saturation=c.signal_count>=300?'authority_ready':c.signal_count>=50?'saturated':c.signal_count>=20?'rising':'emerging'; c.authority_ready=c.signal_count>=150 || c.saturation==='authority_ready'; clusters.set(cluster,c);}
 const existing=readJson(MEMORY,{clusters:[],policy:{}}); const prior=new Map((existing.clusters||[]).map(c=>[c.cluster_id,c])); for(const c of clusters.values()){const old=prior.get(c.cluster_id)||{}; prior.set(c.cluster_id,{...old,...c,signal_count:Number(old.signal_count||0)+c.signal_count,conversion_url:CTA_TARGET,canonical_domain:AUTHORITY_DOMAIN});}
 writeJson(OUT,{generated_at:new Date().toISOString(),policy:{all_signals_get_destination:true,cta_target:CTA_TARGET,authority_domain:AUTHORITY_DOMAIN},routes:routed}); writeJson(MEMORY,{generated_at:new Date().toISOString(),policy:{trigger_based_authority:true,no_firehose:true},clusters:[...prior.values()].sort((a,b)=>(b.signal_count||0)-(a.signal_count||0))}); console.log(`route:signals routed ${routed.length} signals into ${clusters.size} clusters`);}
if(require.main===module) main();
