#!/usr/bin/env bash
set -euo pipefail

mkdir -p docs

cat > docs/OPERATIONS.md <<'MD'
# Operations Runbook

This repo runs as a strict execution engine.

## Primary Commands

- npm run validate:all
- npm run execution:strict
- npm run reddit:daily
- npm run reddit:evening
- npm run admin:build

## Health Standard

The repo is healthy only when all of these are true:

- CANNIBALIZATION CONTRACT PASS
- QUERY COVERAGE PASS
- validate_fanout_warning: OK
- PAGE TYPE CONVERSION FLOOR PASS: warnings=0
- [validate_all] OK

## Normal Operator Flow

1. Pull latest main.
2. Run npm run validate:all.
3. If needed, run npm run execution:strict.
4. Do not manually edit generated pages unless explicitly instructed.
5. Commit only intentional changes.
6. Push to main.
7. Confirm GitHub Actions are green.

## Do Not Touch Without Owner Approval

- scripts/validators/
- scripts/execution/
- scripts/intake/build_backlog_full_coverage.js
- data/scoring/cannibalization_map.json
- .github/workflows/

## Admin

Admin is generated by:

npm run admin:build

Admin password gate:

process.env.SPRY_ADMIN_PASSWORD || "aplayer"

Admin is private/noindex.
MD

cat > docs/SYSTEM_CAPABILITIES.md <<'MD'
# System Capabilities

## Query + Intake

- Build query universe
- Run source ingestion
- Collect queries
- Cluster queries
- Score query clusters
- Build canonical use-case backlog
- Collapse role variants into canonical use cases

## Answer Surface

- Generate observation candidates
- Score answer-surface visibility
- Build dashboard
- Build weakness backlog
- Track score history
- Convert weak clusters into next actions

## Authority

- Build authority graph
- Compute authority scores
- Enforce internal linking
- Validate authority graph integrity

## Conversion

- Enforce conversion floor
- Validate CTA presence
- Validate conversion endpoint
- Require zero conversion warnings

## Automation

- Validate on push
- Validate on pull request
- Strict execution via workflow
- Reddit Daily workflow
- Reddit Evening workflow
- Serialized workflow concurrency
- Auto-commit workflow outputs when intentional

## Admin

- Password-gated dashboard
- Backlog visibility
- Answer-surface visibility
- Reddit visibility
- Authority visibility
- Override visibility

## Current Standard

- 0 high-risk cannibalization collisions
- 24/24 canonical use cases covered
- 0 page-type conversion warnings
- validate_all OK
MD

cat > docs/VA_RUNBOOK.md <<'MD'
# VA Runbook

## What This Site Does

This site is a programmatic authority system designed to generate, validate, and maintain SEO/AEO/LLM visibility pages.

## Daily Check

1. Open GitHub Actions.
2. Confirm these workflows are green:
   - Validate
   - Execution Strict
   - Reddit Daily
   - Reddit Evening
3. If a workflow fails, copy the first red error block and send it to the owner.

## Do Not Do

- Do not manually edit generated HTML pages.
- Do not delete data files.
- Do not change validators.
- Do not change workflow files.
- Do not change conversion endpoint.
- Do not edit admin password logic.
- Do not commit .build, coverage, or reports unless specifically instructed.

## Safe Checks

Run:

git status --short

Then:

npm run validate:all

## If Validation Fails

Send:

- command run
- first error block
- git status --short
- file named in error

## If Push Is Rejected

Run only:

git pull --rebase origin main
git push origin main

If conflict appears, stop and ask owner.
MD

cat > docs/AUTOMATION_MAP.md <<'MD'
# Automation Map

## Validate Workflow

Path:

.github/workflows/validate.yml

Runs on:

- push to main
- pull request

Runs:

npm ci
npm run validate:all

## Execution Strict Workflow

Path:

.github/workflows/execution-strict.yml

Runs on:

- schedule
- workflow_dispatch

Runs:

npm ci
npm run execution:strict

## Reddit Daily / Reddit Evening

Purpose:

- collect Reddit signals
- normalize signals
- cluster questions
- score clusters
- publish or queue where allowed

## Required Concurrency

All committing workflows should use:

concurrency:
  group: main-automation
  cancel-in-progress: false

## Automation Ownership

Execution Strict owns:

- data/answer_surface/
- data/answer_surface_monitoring/
- data/backlog/
- reports/
- coverage/
- .build/

Reddit workflows own:

- data/reddit/

## Conflict Prevention

Reddit workflows should restore non-Reddit generated conflict files before committing:

git restore data/answer_surface data/answer_surface_monitoring data/backlog reports .build coverage || true
MD

cat > docs/VALIDATOR_INVENTORY.md <<'MD'
# Validator Inventory

## Core Validators

- scripts/validators/validate_backlog_contract.js
- scripts/validators/validate_prebuild.js
- scripts/validators/validate_cannibalization.js
- scripts/validators/validate_query_coverage.js
- scripts/validators/validate_conversion_contract.js
- scripts/validators/validate_extractability.js
- scripts/validators/validate_page_type_conversion_floor.js
- scripts/validators/validate_answer_surface_history.js
- scripts/validators/validate_answer_surface_weakness_backlog.js
- scripts/validators/validate_answer_surface_dashboard_gates.js
- scripts/validators/validate_internal_authority_graph.js
- scripts/validators/validate_aeo_contract.js
- scripts/validators/validate_fanout_blocks.js
- scripts/validators/validate_schema_contract.js
- scripts/validators/validate_crawl_contract.js
- scripts/validators/validate_conversion_endpoint.js
- scripts/validators/validate_url_contract.js
- scripts/validators/validate_sitemap_page_parity.js
- scripts/validators/validate_canonical_url_contract.js
- scripts/validators/validate_cta_endpoint_contract.js

## Hard Standards

- Cannibalization: 0 collisions
- Query coverage: 100% canonical use-case coverage
- Fanout: no warnings
- Page-type conversion: warnings=0
- Validation: [validate_all] OK

## Advisory vs Hard Fail

In production strict mode, warnings are not acceptable unless a validator is explicitly documented as advisory.
MD

cat > docs/NEXT_EXECUTION_BACKLOG.md <<'MD'
# Next Execution Backlog

## 1. Interactive Admin v2

Build an interactive admin control panel with:

- filters
- workflow status
- failed validator cards
- latest execution run
- coverage cards
- answer-surface weakness cards
- Reddit run cards
- authority score cards
- override editor
- VA-safe instructions

## 2. Repo Shape Cleanup

Optional. Not urgent.

Potential future cleanup:

- reduce root clutter
- separate generated vs source
- document source vs generated files
- preserve deployed route compatibility

## 3. Workflow Observability

Add dashboard panel showing:

- latest GitHub Action status
- last successful execution
- last Reddit Daily run
- last Reddit Evening run

## 4. Admin Security

Replace client-side password gate with Cloudflare Access or hosting-layer auth.
MD

cat > docs/README.md <<'MD'
# Repo Documentation Index

Read these first:

1. OPERATIONS.md
2. SYSTEM_CAPABILITIES.md
3. AUTOMATION_MAP.md
4. VALIDATOR_INVENTORY.md
5. VA_RUNBOOK.md
6. NEXT_EXECUTION_BACKLOG.md
MD

echo "Repo docs installed:"
find docs -maxdepth 1 -type f | sort
