#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
const ROOT=process.cwd();
const REG=path.join(ROOT,'data/release/frozen_output_registry.json');
const CACHE=path.join(ROOT,'data/release/frozen_accepted_outputs');
const SCOPE=path.join(ROOT,'data/release/active_mutation_scope.json');
const ADMISSION=path.join(ROOT,'data/content/page_admission_registry.json');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const normalizeRoute=r=>{r=String(r||'').trim();if(!r)return'';if(!r.startsWith('/'))r='/'+r;return r==='/'?'/':r.replace(/\/$/,'')+(String(r).endsWith('.html')?'':'/');};
const routeFromPath=p=>{p=String(p||'').replace(/^\.\//,'');if(!p)return'';if(p.endsWith('/index.html'))return '/'+p.slice(0,-'index.html'.length);if(p.endsWith('.html'))return '/'+p;return '/'+p.replace(/^\//,'');};
const load=(p,f)=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf8')):f;
const registry=()=>load(REG,{schema_version:'1.0',policy:'accepted_output_freeze',source_registry:'data/content/page_admission_registry.json',accepted_statuses:['ADMITTED'],mutation_scope:'data/release/active_mutation_scope.json',records:{}});
const scope=()=>new Set((load(SCOPE,{routes:[]}).routes||[]).map(normalizeRoute));
function admitted(){const d=load(ADMISSION,{records:[],pages:[]});const out=[];for(const r of d.records||[])if(String(r.status).toUpperCase()==='ADMITTED'&&r.path)out.push({route:normalizeRoute(r.route||routeFromPath(r.path)),path:r.path});for(const r of d.pages||[])if(String(r.status).toLowerCase()==='admitted'&&r.path)out.push({route:normalizeRoute(routeFromPath(r.path)),path:r.path});const m=new Map();for(const r of out)if(r.route&&r.path&&fs.existsSync(path.join(ROOT,r.path)))m.set(r.route,r);return [...m.values()];}
// status also reports missing_cache. A record whose sha256 is updated without its
// gzip blob being written leaves restore() with nothing to restore from, and
// restore() exits 1 - so the release lane dies on the FIRST step that touches the
// cache, with no earlier signal. That is exactly what happened to /download.html:
// the registry hash was updated by 7c96aab61, the blob was never written, and every
// release run failed there until the blob was regenerated. Checking it here surfaces
// the same condition from a cheap status call instead of a dead release lane.
function status(){const reg=registry(),allowed=scope();let drift=0,missing=0,missingCache=0;for(const [route,r] of Object.entries(reg.records||{})){if(!fs.existsSync(path.join(ROOT,r.blob||'')))missingCache++;const p=path.join(ROOT,r.path);if(!fs.existsSync(p)){missing++;continue;}if(!allowed.has(normalizeRoute(route))&&hash(fs.readFileSync(p))!==r.sha256)drift++;}console.log(JSON.stringify({command:'status',frozen:Object.keys(reg.records||{}).length,active_mutation_routes:allowed.size,unscoped_drift:drift,missing_rendered:missing,missing_cache:missingCache},null,2));if(drift||missing||missingCache)process.exit(1);}
function restore(){const reg=registry(),allowed=scope();let restored=0,thawed=0,missing=0;for(const [route,r] of Object.entries(reg.records||{})){if(allowed.has(normalizeRoute(route))){thawed++;continue;}const blob=path.join(ROOT,r.blob||'');if(!fs.existsSync(blob)){missing++;continue;}const raw=zlib.gunzipSync(fs.readFileSync(blob));const p=path.join(ROOT,r.path);const cur=fs.existsSync(p)?hash(fs.readFileSync(p)):null;if(cur!==r.sha256){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,raw);restored++;}}console.log(JSON.stringify({command:'restore',restored,transactionally_thawed:thawed,missing_cache:missing},null,2));if(missing)process.exit(1);}
function collectScope(){const routes=new Set();const add=(r)=>{const n=normalizeRoute(r);if(n)routes.add(n);};const plan=load(path.join(ROOT,'artifacts/validation/daily-citation-release-plan.json'),{});for(const r of plan.selected||[]){add(r.route_owner);if(r.source_file)add(routeFromPath(r.source_file));}const agent=load(path.join(ROOT,'artifacts/validation/agent-exact-implementation-plan.json'),{});for(const s of agent.specs||[]){if(s.status==='PLANNED'&&s.implementation_path)add(routeFromPath(s.implementation_path));}fs.mkdirSync(path.dirname(SCOPE),{recursive:true});fs.writeFileSync(SCOPE,JSON.stringify({schema_version:'1.0',generated_at:new Date().toISOString(),sources:['daily-citation-release-plan','agent-exact-implementation-plan'],routes:[...routes].sort()},null,2)+'\n');console.log(JSON.stringify({command:'prepare-scope',routes:routes.size},null,2));}
function freeze(){const old=registry(),allowed=scope();const unscoped=[];for(const [route,r] of Object.entries(old.records||{})){const p=path.join(ROOT,r.path);if(!fs.existsSync(p))continue;const h=hash(fs.readFileSync(p));if(h!==r.sha256&&!allowed.has(normalizeRoute(route)))unscoped.push({route,path:r.path,before:r.sha256,after:h});}if(unscoped.length){console.error(JSON.stringify({error:'UNSCOPED_FROZEN_OUTPUT_DRIFT',count:unscoped.length,sample:unscoped.slice(0,20)},null,2));process.exit(1);}fs.mkdirSync(CACHE,{recursive:true});const records={};for(const a of admitted()){const raw=fs.readFileSync(path.join(ROOT,a.path));const h=hash(raw);const blob=`data/release/frozen_accepted_outputs/${h}.html.gz`;const abs=path.join(ROOT,blob);if(!fs.existsSync(abs))fs.writeFileSync(abs,zlib.gzipSync(raw,{level:9,mtime:0}));records[a.route]={path:a.path,sha256:h,blob};}const keep=new Set(Object.values(records).map(r=>path.basename(r.blob)));for(const n of fs.readdirSync(CACHE))if(n.endsWith('.html.gz')&&!keep.has(n))fs.rmSync(path.join(CACHE,n),{force:true});const out={schema_version:'1.1',policy:'accepted_output_freeze',source_registry:'data/content/page_admission_registry.json',accepted_statuses:['ADMITTED','admitted'],mutation_scope:'data/release/active_mutation_scope.json',records};fs.writeFileSync(REG,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({command:'freeze',frozen:Object.keys(records).length,accepted_mutation_routes:allowed.size,unscoped_drift:0},null,2));}
function collectDriftScope(){const reg=registry();const routes=new Set([...scope()]);let scanned=0,changed=0,missing=0;for(const [route,r] of Object.entries(reg.records||{})){scanned++;const p=path.join(ROOT,r.path);if(!fs.existsSync(p)){missing++;continue;}const h=hash(fs.readFileSync(p));if(h!==r.sha256){routes.add(normalizeRoute(route));changed++;}}fs.mkdirSync(path.dirname(SCOPE),{recursive:true});const existing=load(SCOPE,{sources:[]});fs.writeFileSync(SCOPE,JSON.stringify({schema_version:'1.0',generated_at:new Date().toISOString(),sources:[...new Set([...(existing.sources||[]),'frozen-output-drift-diff'])],mode:'exact_post_run_changed_routes',scanned_frozen_routes:scanned,changed_frozen_routes:changed,missing_rendered_routes:missing,routes:[...routes].sort()},null,2)+'\n');console.log(JSON.stringify({command:'prepare-drift-scope',routes:routes.size,changed_frozen_routes:changed,missing_rendered_routes:missing},null,2));if(missing)process.exit(1);}
function clear(){fs.rmSync(SCOPE,{force:true});console.log(JSON.stringify({command:'clear-scope',cleared:true},null,2));}
const cmd=process.argv[2]||'status';const fn={status,restore,freeze,'prepare-scope':collectScope,'prepare-drift-scope':collectDriftScope,'clear-scope':clear}[cmd];if(!fn)throw new Error(`Unknown command ${cmd}`);fn();
