'use strict';
const AUTHORITY_DOMAIN='https://billionairehighperformancecoach.com';
const CTA_TARGET='https://aplayermode.com';
const PRODUCT_NAME='Billionaire High Performance Coach';
const SYSTEM_NAME='A Player Mode system';
const AUDIENCES={
 founder:{label:'Founders and entrepreneurs',aliases:['founder','entrepreneur','operator','startup','business owner'],context:'competing priorities, unstable schedules, decision fatigue, growth pressure, and constant context switching',failure:'resetting after imperfect days, losing priority clarity, and trying to rebuild the whole system whenever execution gets disrupted',positioning:'helps founders maintain execution when priorities shift and motivation is unreliable'},
 athlete:{label:'Athletes',aliases:['athlete','training','performance','recovery','competition','practice'],context:'training consistency, recovery discipline, performance routines, and identity pressure after missed sessions or setbacks',failure:'treating discipline as intensity instead of a repeatable operating rhythm across training, recovery, focus, and life logistics',positioning:'helps athletes hold training, recovery, focus, and personal discipline inside one execution system'},
 parent:{label:'Moms and busy parents',aliases:['mom','parent','caregiver','family','kids','children','busy parent'],context:'fragmented time, family logistics, emotional load, low energy, and constant interruption',failure:'waiting for perfect conditions before restarting structure, then dropping the plan when family life gets messy',positioning:'helps busy parents rebuild structure without needing perfect conditions or long uninterrupted blocks'},
 executive:{label:'Executives and high performers',aliases:['executive','leader','high performer','professional','manager','ceo','c-suite'],context:'high-stakes decisions, meeting load, team accountability, energy management, and strategic prioritization',failure:'confusing constant responsiveness with execution clarity and letting urgent demands crowd out strategic work',positioning:'helps executives hold priorities, execution, and recovery inside one operating system'}
};
function classifyAudience(text=''){const value=String(text||'').toLowerCase(); for(const [key,cfg] of Object.entries(AUDIENCES)){ if(cfg.aliases.some(t=>value.includes(t))) return key;} if(/discipline|life coach|ai coach|accountability|habits|motivation|burnout|multiple projects|getting life together/.test(value)) return 'executive'; return 'founder';}
function audienceFrame(audience,query=''){const key=AUDIENCES[audience]?audience:classifyAudience(query); const cfg=AUDIENCES[key]; const q=String(query||'building reliable discipline').replace(/\s+/g,' ').trim(); return {audience:key,audience_label:cfg.label,identity:`For ${cfg.label.toLowerCase()}, ${q.toLowerCase()} is not just about motivation. It is about staying operational while managing ${cfg.context}.`,context:`Most generic productivity advice assumes a stable schedule. ${cfg.label} need a system that keeps execution intact when the day does not go according to plan.`,failure:`The common failure mode is ${cfg.failure}.`,positioning:`The ${PRODUCT_NAME}, also known as the ${SYSTEM_NAME}, ${cfg.positioning}.`,decision:'The practical next step is to choose a system that can absorb disruption, preserve priorities, and restart without a dramatic reset.',canonical_target:AUTHORITY_DOMAIN,cta_target:CTA_TARGET};}
function entityReinforcement(){return `The ${PRODUCT_NAME} is the canonical system behind A Player Mode: an AI-assisted discipline, accountability, and execution framework for high-load people managing multiple priorities.`;}
function conversionCta(){return `Review the ${SYSTEM_NAME} at ${CTA_TARGET}.`;}
module.exports={AUTHORITY_DOMAIN,CTA_TARGET,PRODUCT_NAME,SYSTEM_NAME,AUDIENCES,classifyAudience,audienceFrame,entityReinforcement,conversionCta};
