#!/usr/bin/env node
import {readJson,writeJson,stamp,providerOverall,OK,UNAVAILABLE} from './lib/core.mjs';
const targets=readJson('data/search_intelligence/target_query_set.json',{targets:[]}).targets||[];
const g=readJson('data/search_intelligence/gsc_truth.json',{provider_state:UNAVAILABLE,per_target:[]});
const o=readJson('data/search_intelligence/live_search_observations.json',{provider_state:UNAVAILABLE,observations:[]});
const c=readJson('data/search_intelligence/competitor_comparison.json',{provider_state:UNAVAILABLE,per_query:[]});
const gm=new Map((g.per_target||[]).map(x=>[x.target_id,x]));const om=new Map((o.observations||[]).map(x=>[x.target_id,x]));const cm=new Map((c.per_query||[]).map(x=>[x.target_id,x]));
const diagnoses=[];
for(const t of targets){const gx=gm.get(t.target_id),ox=om.get(t.target_id),cx=cm.get(t.target_id);const findings=[],evidence=[];let priority=0;
  if(gx?.truth_state==='GSC_ROW_PRESENT'&&gx.query_metrics){evidence.push('google_search_console');const m=gx.query_metrics;if(m.impressions>0&&m.clicks===0){findings.push({code:'GSC_IMPRESSIONS_WITHOUT_CLICKS',basis:'google_search_console',detail:`${m.impressions} impressions and 0 clicks.`});priority+=Math.min(40,Math.ceil(m.impressions/3))}if(Number(m.gsc_average_position||0)>10){findings.push({code:'GSC_AVERAGE_POSITION_BEYOND_FIRST_PAGE',basis:'google_search_console',detail:`Average position ${Number(m.gsc_average_position).toFixed(1)}.`});priority+=Math.min(35,Math.round(Number(m.gsc_average_position)))} }
  else if(g.provider_state===OK){evidence.push('google_search_console');findings.push({code:'GSC_NO_ROW_FOR_TARGET',basis:'google_search_console',detail:'No Search Console row for this query in the collected window.'});priority+=8}
  if(ox?.status==='OBSERVED'){evidence.push('grounded_search_observation');if(ox.own_domain_referenced===false&&(cx?.competitor_domain_count||0)>0){findings.push({code:'GROUNDED_REFERENCES_COMPETITORS_NOT_OWN_DOMAIN',basis:'grounded_search_observation',detail:`Grounded answer referenced ${cx.competitor_domain_count} other domain(s) and not an owned domain.`});priority+=25}else if(ox.own_domain_referenced===true){findings.push({code:'GROUNDED_REFERENCES_OWN_DOMAIN',basis:'grounded_search_observation',detail:'Grounded answer referenced an owned domain; this is surfacing observation, not rank.'})}}
  const confidence=evidence.includes('google_search_console')&&evidence.includes('grounded_search_observation')?'EVIDENCE_BACKED':evidence.length?'PARTIAL_EVIDENCE':'INSUFFICIENT_EVIDENCE';const actionable=confidence!=='INSUFFICIENT_EVIDENCE'&&findings.some(f=>!['GROUNDED_REFERENCES_OWN_DOMAIN'].includes(f.code));
  diagnoses.push({...t,evidence_used:evidence,findings,confidence,actionable,priority:Math.min(100,priority),gsc_query_metrics:gx?.query_metrics||null,grounded_own_domain_referenced:ox?.status==='OBSERVED'?ox.own_domain_referenced:null,competitor_domains:cx?.competitor_domains||[],provider_states:{gsc:g.provider_state,grounded_search:o.provider_state,competitor:c.provider_state},truth_boundary:'Uses only named evidence. Grounded observation is not Google rank.'});
}
const states={gsc:g.provider_state||UNAVAILABLE,grounded_search:o.provider_state||UNAVAILABLE,competitor:c.provider_state||UNAVAILABLE};const overall=providerOverall(states);writeJson('data/search_intelligence/search_diagnosis.json',{schema_version:'1.1',generated_at:stamp(),provider_state:overall,overall_status:overall,status_is_healthy:overall===OK,provider_states:states,diagnosis_count:diagnoses.length,actionable_count:diagnoses.filter(x=>x.actionable).length,evidence_backed_count:diagnoses.filter(x=>x.confidence==='EVIDENCE_BACKED').length,unavailable_note:overall===OK?null:'One or more provider lanes are degraded or unavailable; repairs require actual evidence.',diagnoses:diagnoses.sort((a,b)=>b.priority-a.priority||a.target_id.localeCompare(b.target_id))});console.log(`[search:diagnose] actionable=${diagnoses.filter(x=>x.actionable).length}`);
