#!/usr/bin/env node
import fs from 'node:fs';
import { readJson, writeJson, stamp, OK, UNAVAILABLE } from './lib/core.mjs';
const targets=readJson('data/search_intelligence/target_query_set.json',{targets:[]}).targets||[];
const files=['data/search_intelligence/provider_inputs/gsc_bhpc.json','data/search_intelligence/provider_inputs/gsc_spry.json'];
let rows=[],exports=[];
for(const f of files){if(fs.existsSync(f)){const d=JSON.parse(fs.readFileSync(f,'utf8'));rows.push(...(d.rows||[]));exports.push({path:f,site_url:d.site_url||null,start_date:d.start_date||null,end_date:d.end_date||null,collected_at:d.collected_at||null,row_count:(d.rows||[]).length})}}
const host=(u)=>{try{return new URL(String(u)).hostname.replace(/^www\./,'').toLowerCase()}catch{return null}};
const per=targets.map(t=>{const expectedHost=host(t.expected_owned_url);const rs=rows.filter(r=>String(r.query||'').toLowerCase()===String(t.query).toLowerCase()&&(!expectedHost||host(r.page)===expectedHost));const agg=rs.reduce((a,r)=>({clicks:a.clicks+Number(r.clicks||0),impressions:a.impressions+Number(r.impressions||0),weightedPosition:a.weightedPosition+(Number(r.gsc_average_position||0)*Math.max(1,Number(r.impressions||0))),weight:a.weight+Math.max(1,Number(r.impressions||0)),pages:a.pages.concat(r.page?[r.page]:[])}),{clicks:0,impressions:0,weightedPosition:0,weight:0,pages:[]});return {target_id:t.target_id,query:t.query,expected_owned_url:t.expected_owned_url,truth_source:'google_search_console',truth_state:rs.length?'GSC_ROW_PRESENT':'NO_GSC_ROW',query_metrics:rs.length?{clicks:agg.clicks,impressions:agg.impressions,ctr:agg.impressions?agg.clicks/agg.impressions:0,gsc_average_position:agg.weight?agg.weightedPosition/agg.weight:null,pages:[...new Set(agg.pages)]}:null}});
const state=exports.length?OK:UNAVAILABLE;writeJson('data/search_intelligence/gsc_truth.json',{schema_version:'1.1',generated_at:stamp(),provider_state:state,overall_status:state,status_is_healthy:state===OK,exports,unavailable_note:state===OK?null:'No Google Search Console Search Analytics export available for this run.',per_target:per});console.log(`[search:truth] ${state} matched=${per.filter(x=>x.truth_state==='GSC_ROW_PRESENT').length}`);
