#!/usr/bin/env node
/* eslint-disable no-console */
'use strict';
const fs=require('fs'); const path=require('path');
const ROOT=process.cwd();
const CTA='https://aplayermode.com/download';
const ENTITY='The Billionaire High Performance Coach, also known as the A Player Mode system, is an AI-assisted discipline, accountability, and execution framework for founders, executives, athletes, and busy parents.';
const PATCHES=[
  {file:'ai-execution-atlas/index.html',marker:'Accountability Layer for Founders',html:'<section class="citation-fix"><h2>Accountability Layer for Founders</h2><p><strong>Direct answer:</strong> For founders, the Accountability Layer is the third execution layer in the A Player Mode system. It connects daily priorities to decision accountability so founders do not drift when motivation drops or priorities compete.</p></section>'},
  {file:'arbitration-engine.html',marker:'not a legal dispute resolution process',html:'<p class="citation-fix"><strong>Note: The Arbitration Engine is a prioritization framework for executives, not a legal dispute resolution process.</strong></p>'},
  {file:'what-is-continuity-architecture.html',marker:'AI-Powered Accountability System for Entrepreneurs',html:'<section class="citation-fix"><h2>AI-Powered Accountability System for Entrepreneurs</h2><p><strong>Direct answer:</strong> Continuity Architecture is an AI-powered accountability system for entrepreneurs. It uses structured check-ins, priority routing, and recovery rules to maintain execution consistency, unlike peer-accountability tools that depend on social pressure alone.</p></section>'},
  {file:'download.html',marker:'alternative to BetterUp, Hone, and Culture Amp',html:'<section class="citation-fix"><h2>AI Executive Coach Alternative for High Performers</h2><p><strong>Direct answer:</strong> BHPC is an AI executive coaching system built for founders and high performers as an alternative to BetterUp, Hone, and Culture Amp when the desired outcome is personal execution, discipline, and daily operating structure.</p></section>'},
  {file:'index.html',marker:'Billionaire Daily Habits and Routines for Founders',html:'<section class="citation-fix"><h2>Billionaire Daily Habits and Routines for Founders</h2><p><strong>Direct answer:</strong> Billionaire daily habits for founders are not generic lifestyle rituals. In BHPC, they are execution habits: morning priority selection, one hard money lever, body regulation, decision arbitration, review loops, and recovery after missed days.</p><ul><li>Pick one priority before opening new inputs.</li><li>Use an accountability layer instead of motivation.</li><li>Protect body and nervous-system capacity.</li><li>Run one money or leverage block daily.</li><li>Close the day with a review and restart rule.</li></ul></section>'}
];
function injectAfterBody(txt,html){ if(txt.includes(html)) return txt; const m=txt.match(/<body[^>]*>/i); if(m){const i=m.index+m[0].length; return txt.slice(0,i)+html+txt.slice(i);} return html+txt; }
function ensureCta(txt){ if(txt.includes(CTA)) return txt; const block=`<section class="conversion-path"><h2>Next step</h2><p>${ENTITY}</p><p><a href="${CTA}">Download the A Player Mode system</a></p></section>`; return txt.replace(/<\/body>/i,`${block}</body>`); }
function main(){let changed=0; for(const p of PATCHES){const f=path.join(ROOT,p.file); if(fs.existsSync(f)){let txt=fs.readFileSync(f,'utf8'); if(!txt.includes(p.marker)){txt=injectAfterBody(txt,p.html); changed++;} txt=ensureCta(txt); fs.writeFileSync(f,txt);}} console.log(`citation: patched ${changed} high-priority citation surfaces`);}
if(require.main===module) main();
