#!/usr/bin/env node
/* eslint-disable no-console */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = process.cwd();
const MEMORY = path.join(ROOT, 'data/content_clusters/cluster_memory.json');
const COVERAGE = path.join(ROOT, 'data/query_coverage_map.json');
const SOCIAL_RUNS = path.join(ROOT, 'data/social/runs');
const REDDIT_QUERIES = path.join(ROOT, 'data/reddit/queries.json');
const CONVERSION_URL = 'https://aplayermode.com';
const CANONICAL_DOMAIN = 'https://billionairehighperformancecoach.com';
const AUDIENCES = ['professionals','entrepreneurs','athletes','moms/caregivers','multi-project operators'];
function readJson(file, fallback){ try { return JSON.parse(fs.readFileSync(file,'utf8')); } catch { return fallback; } }
function writeJson(file, data){ fs.mkdirSync(path.dirname(file), {recursive:true}); fs.writeFileSync(file, JSON.stringify(data,null,2)+'\n'); }
function slug(s){ return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80) || 'general'; }
function clusterId(text){ const v=String(text||'').toLowerCase(); if(/discipline|consistency|follow through|habit/.test(v)) return 'discipline-consistency'; if(/ai|chatgpt|assistant|automation|tool/.test(v)) return 'ai-executive-coaching'; if(/burnout|overwhelmed|juggling|too much|multiple projects|decision fatigue/.test(v)) return 'burnout-overload-multi-track'; if(/planning|daily plan|weekly review|priorit/.test(v)) return 'planning-review-systems'; if(/coach|life coach|executive coach|accountability/.test(v)) return 'coaching-accountability'; return slug(text).slice(0,48); }
function intent(text){ const v=String(text||'').toLowerCase(); if(/cost|price|worth|buy|download/.test(v)) return 'conversion'; if(/best|compare|vs|tool|coach/.test(v)) return 'provider_selection'; if(/how|system|framework|routine|plan/.test(v)) return 'process'; if(/burnout|overwhelmed|stuck|fail/.test(v)) return 'pain'; return 'general'; }
function loadSignals(){ const out=[]; if(fs.existsSync(SOCIAL_RUNS)){ for(const f of fs.readdirSync(SOCIAL_RUNS).filter(x=>x.endsWith('.json')).sort().slice(-14)){ const run=readJson(path.join(SOCIAL_RUNS,f),{}); for(const r of run.records||[]) out.push({source:'social', platform:r.platform, title:r.title||r.term||'', excerpt:r.excerpt||'', score:r.score||0, captured_at:r.captured_at||run.generated_at}); } } const reddit=readJson(REDDIT_QUERIES,{queries:[]}); for(const q of reddit.queries||[]) out.push({source:'reddit', platform:'reddit', title:q.query||q.title||q.normalized_query||'', excerpt:q.answer||q.notes||'', score:q.score||0, captured_at:q.captured_at}); return out; }
function main(){ const previous=readJson(MEMORY,{clusters:[],policy:{}}); const prevMap=new Map((previous.clusters||[]).map(c=>[c.cluster_id,c])); const signals=loadSignals(); for(const sig of signals){ const text=`${sig.title} ${sig.excerpt}`.trim(); if(!text) continue; const id=clusterId(text); const existing=prevMap.get(id)||{cluster_id:id, signal_count:0, signals:[], first_seen:new Date().toISOString(), status:'emerging'}; existing.signal_count += 1; existing.last_updated = new Date().toISOString(); existing.intent_type = intent(text); existing.audiences = AUDIENCES.filter(a=> new RegExp(a.split('/')[0].replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i').test(text)); if(!existing.audiences.length) existing.audiences = AUDIENCES; existing.authority_potential = Math.min(100, Math.round((existing.signal_count*3) + (Number(sig.score||0)/2))); existing.saturation = existing.signal_count >= 50 ? 'saturated' : existing.signal_count >= 20 ? 'rising' : 'emerging'; existing.conversion_url = CONVERSION_URL; existing.canonical_domain = CANONICAL_DOMAIN; existing.signals = [...(existing.signals||[]), {title:sig.title, source:sig.source, platform:sig.platform, captured_at:sig.captured_at}].slice(-50); prevMap.set(id, existing); }
 const clusters=[...prevMap.values()].sort((a,b)=>(b.authority_potential||0)-(a.authority_potential||0)); writeJson(MEMORY,{generated_at:new Date().toISOString(),policy:previous.policy||{},clusters}); const coverage=readJson(COVERAGE,{}); const covered=clusters.map(c=>({cluster_id:c.cluster_id,intent_type:c.intent_type,signal_count:c.signal_count,saturation:c.saturation,canonical_anchor:(coverage.canonical_anchors||[])[0]||'/',conversion_url:CONVERSION_URL})); const gaps=clusters.filter(c=>c.signal_count>=5 && !String(c.status||'').includes('covered')).map(c=>({cluster_id:c.cluster_id,reason:'cluster has repeated demand but no confirmed synthesis/authority coverage'})); writeJson(COVERAGE,{...coverage,generated_at:new Date().toISOString(),covered_queries:covered,gaps:gaps.slice(0,50)}); console.log(`content_clusters: tracked ${clusters.length} clusters from ${signals.length} signals`); }
if(require.main===module) main();
