#!/usr/bin/env bash
set -euo pipefail
run(){ echo "[validate:content] $*"; "$@"; }
run node scripts/validators/validate_use_case_taxonomy_mapping.js
run node scripts/validators/validate_no_patch_artifacts.js
run node scripts/validators/validate_backlog_contract.js
run node scripts/validators/validate_prebuild.js
run node scripts/validators/validate_signal_floor.js
run node scripts/validators/validate_scoring_contract.js
run node scripts/validators/validate_answer_surface_strength.js
run node scripts/validators/validate_answer_surface_history.js
run node scripts/validators/validate_answer_surface_weakness_backlog.js
run node scripts/validators/validate_answer_surface_dashboard_gates.js
run node scripts/validators/validate_cannibalization.js
run node scripts/validators/validate_intake_taxonomy_contract.js
run node scripts/validators/validate_query_universe_contract.js
run node scripts/validators/validate_conversion_contract.js
run node scripts/validators/validate_machine_readability_contract.js
run node scripts/validators/validate_social_firehose_contract.js
run node scripts/validators/validate_throttle_contract.js
run node scripts/validators/validate_vertical_keys.js
run node scripts/validators/validate_content_routing.js
run node scripts/validators/validate_extractability.js
run node scripts/validators/validate_priority_llm_surfaces.js
run node scripts/prepare_distribution_artifacts.js
run node scripts/validators/legacy_ops/validate_distribution_contract.js
run node scripts/validators/legacy_ops/validate_dual_domain_contract.js
run node scripts/validators/legacy_ops/validate_internal_links.js
run node scripts/validators/legacy_ops/validate_reddit_publish_contract.js
run node scripts/validators/legacy_ops/validate_reddit_uniqueness.js
run node scripts/validate_geo_semantics.js
run node scripts/validate_content_routing.js
run node scripts/validate_audience_framing.js
run node scripts/validate_conversion_targets.js
run node scripts/validators/validate_destination_contracts.js
run node scripts/validators/validate_above_fold.js
run node scripts/validators/validate_cta_presence.js
run node scripts/validators/validate_authority_engine.js
run node scripts/validators/validate_word_count.js
run node scripts/validators/validate_author_trust.js
run node scripts/validators/validate_entity_coverage.js
run node scripts/validators/validate_query_metadata.js
run node scripts/validators/validate_query_traceability.js
run env QUERY_COVERAGE_STRICT=1 node scripts/validators/validate_query_coverage.js
run node scripts/validators/validate_authority_scores.js
run node scripts/validators/validate_internal_authority_graph.js
run node scripts/validators/validate_money_link_floor.js
run node scripts/validators/validate_aeo_contract.js
run node scripts/validators/validate_fanout_blocks.js
run node scripts/validators/validate_schema_contract.js
run node scripts/validators/validate_crawl_contract.js
run node scripts/validators/validate_conversion_endpoint.js
run node scripts/validators/validate_url_contract.js
run node scripts/validators/validate_sitemap_page_parity.js
run node scripts/validators/validate_canonical_url_contract.js
run node scripts/validators/validate_cta_endpoint_contract.js
run env PAGE_TYPE_CONVERSION_STRICT=1 node scripts/validators/validate_page_type_conversion_floor.js
run node scripts/validators/validate_citation_readiness_warning.js
echo "[validate:content] OK"
