import fs from 'node:fs';
import {decide,rewriteUnsafe,stableId} from '../lib/safe_harbor_utils.mjs';
export function readJson(path,fallback){if(!fs.existsSync(path)){if(arguments.length>1)return fallback;throw new Error(`Missing JSON: ${path}`);}return JSON.parse(fs.readFileSync(path,'utf8'));}
export function writeJson(path,payload){fs.mkdirSync(path.split('/').slice(0,-1).join('/')||'.',{recursive:true});fs.writeFileSync(path,JSON.stringify(payload,null,2)+'\n');}
export function normalizeSlug(text){return String(text||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,90)||'untitled';}
export function loadNormalized(){return readJson('data/signals/normalized/latest_normalized_signals.json',{records:[]}).records||[];}
export function loadOwnership(){const rows=readJson('data/content_ownership_registry.json',{routes:[]}).routes||[];return new Map(rows.map(r=>[String(r.source_file||'').replace(/^\//,''),r]));}
export function buildClusters(records){const groups=new Map();for(const r of records){const key=`${r.page_family}:${r.intent}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}return [...groups.entries()].map(([key,items],i)=>({cluster_id:`spry_cluster_${String(i+1).padStart(3,'0')}`,key,page_family:items[0].page_family,intent:items[0].intent,signals:items.map(x=>x.normalized_id),representative_query:items[0].query,risk_level:items.some(x=>x.risk_level==='high')?'high':items.some(x=>x.risk_level==='medium')?'medium':'low'}));}
export function scoreRecords(records){return records.map(r=>{const base={create:78,repair:72,atom_update:68,internal_link_update:62,answer_block_update:65,entity_context_update:65,schema_update:58,source_update:57,distribution_update:56,block:0,quarantine:0}[r.candidate_action]??30;const riskPenalty=r.risk_level==='high'?40:r.risk_level==='medium'?10:0;return {...r,score:Math.max(0,base-riskPenalty),score_basis:['action value','traffic intent','Spry authority fit','risk penalty']};});}
export function candidateFromScore(r){const action=r.risk_level==='high'||['block','quarantine'].includes(r.candidate_action)?'block':r.candidate_action;const route=r.route_owner||`/${normalizeSlug(r.query)}/`;return {candidate_id:`candidate_${r.normalized_id}`,action,route_owner:route,title:r.title||r.query,query:r.query,page_family:r.page_family||'answer',source_basis:r.source_basis||[],expected_aeo_geo_seo_role:{aeo:r.aeo_role,geo:r.geo_role,seo:r.seo_role},traffic_intent:r.traffic_intent,risk_level:r.risk_level||'low',score:r.score,status:action==='block'?'BLOCKED':'CANDIDATE'};}
function routeFile(route){const clean=String(route||'').replace(/^\//,'');return clean.endsWith('.html')?clean:`${clean.replace(/\/$/,'')}/index.html`;}
export function planFromCandidates(candidates){const ownership=loadOwnership();const velocityDecision=readJson('data/authority_scale/velocity_decision.json',{recommended_new_url_ceiling_per_day:25});const target=Math.max(1,Number(process.env.ZERO_DOLLAR_DAILY_PAGE_TARGET||velocityDecision.recommended_new_url_ceiling_per_day||25));const selected=[],skipped=[],blocked=[];const seen=new Set();const allowFixture=process.env.ALLOW_FIXTURE_MUTATION==='1';for(const c of [...candidates].sort((a,b)=>(b.score||0)-(a.score||0))){const file=routeFile(c.route_owner);const own=ownership.get(file);const duplicate=seen.has(normalizeSlug(c.query));seen.add(normalizeSlug(c.query));const d=decide({owner:own?.owner||'legacy_eligible',action:c.action,text:`${c.title} ${c.query}`,duplicate,route:c.route_owner});const fixture=JSON.stringify(c.source_basis||[]).toLowerCase().includes('fixture');const row={...c,source_file:file,content_owner:own?.owner||'zero_dollar',safe_harbor:d.decision,safe_harbor_reason:d.reason,action_id:stableId([c.candidate_id,file,c.action])};if(fixture&&!allowFixture){skipped.push({...row,decision:'SKIPPED_FIXTURE_ONLY',safe_harbor_reason:'fixture signals are proof-only and cannot mutate public content'});continue;}if(c.status==='BLOCKED'||c.risk_level==='high'||c.action==='block'){blocked.push({...row,decision:'SKIPPED_UNSUPPORTED_CLAIM'});continue;}if(d.decision.startsWith('SKIPPED')){skipped.push(row);continue;}if(selected.length<target)selected.push({...row,decision:'SAFE_AUTOPUBLISH'});else skipped.push({...row,decision:'SKIPPED_CADENCE_TARGET',safe_harbor_reason:'non-blocking daily target reached'});}const stop_reason=planStopReason({candidates,selected,skipped,blocked,allowFixture});return {schema_version:'2.0',repo:'seq23/sprylabs-hpc-site',generated_at:new Date().toISOString(),mode:'FULL_SAFE_AUTONOMY_GAP_FILL',external_telemetry_present:false,stop_reason,selected,skipped,blocked,summary:{release_units_planned:candidates.length,selected_units:selected.length,skipped_units:skipped.length,blocked_units:blocked.length,blocked_units_reasons:reasonHistogram(skipped.concat(blocked)),public_mutation:'SAFE_HARBOR_AUTOPUBLISH'}};}

// Rule 0 support: a plan that selected nothing must be able to say WHY, by name.
// Returns null when the lane did real work.
export function reasonHistogram(rows){const h={};for(const r of rows||[]){const k=r.decision||r.safe_harbor||'SKIPPED';h[k]=(h[k]||0)+1;}return h;}
export function planStopReason({candidates,selected,skipped,blocked,allowFixture}){
  if((selected||[]).length>0)return null;
  if(!(candidates||[]).length)return {code:'NO_CANDIDATES',message:'No release candidates were produced upstream. Check firehose:collect / signals:candidates - the signal chain yielded nothing to plan.'};
  const hist=reasonHistogram((skipped||[]).concat(blocked||[]));
  const fixtureOnly=hist.SKIPPED_FIXTURE_ONLY||0;
  if(fixtureOnly===(candidates||[]).length&&!allowFixture)return {code:'ALL_CANDIDATES_FIXTURE_ONLY',message:`All ${candidates.length} candidate(s) came from fixture signals, which are proof-only and may not mutate public content. No enabled non-fixture source produced records. Supply data/signals/manual_import.json, or enable a credentialed source in data/signals/source_registry.json. This lane cannot do work until a real signal source exists.`,decision_histogram:hist};
  return {code:'ALL_CANDIDATES_SKIPPED',message:`All ${candidates.length} candidate(s) were skipped or blocked; none reached publication.`,decision_histogram:hist};
}
export function renderAnswerPage(item){const title=rewriteUnsafe(item.title||item.query||'BHPC Answer');const q=rewriteUnsafe(item.query||title);const answer=`${title} is best approached as a structured execution question: define the outcome, choose the smallest useful next action, and preserve continuity instead of relying on motivation.`;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>${title} | Spry Executive OS</title><meta name="description" content="A plain-English BHPC answer for ${q}."><link rel="canonical" href="https://spryexecutiveos.com/${item.source_file.replace(/index\.html$/,'')}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:title,dateModified:new Date().toISOString().slice(0,10),author:{'@type':'Organization',name:'Spry Labs'}})}</script></head><body><main><article data-zero-dollar-owned="true" data-safe-harbor="SAFE_AUTOPUBLISH"><p><a href="/">Spry Executive OS</a></p><h1>${title}</h1><section aria-labelledby="direct-answer"><h2 id="direct-answer">Direct answer</h2><p>${answer}</p></section><section><h2>How to use this</h2><ol><li>Name the decision or execution problem.</li><li>Choose one concrete next action.</li><li>Set a minimum viable version for difficult days.</li><li>Review what worked and continue without a reset.</li></ol></section><section><h2>What this does not promise</h2><p>This is an educational execution framework, not medical, legal, financial, or therapeutic advice, and it does not guarantee a specific outcome.</p></section><p><a href="/download">Explore the Billionaire High Performance Coach operating system</a></p></article></main></body></html>`;}
